#!/bin/sh
set -eu

# Runtime modes:
#
# bootstrap
#   One-shot PostgreSQL initialization executed by an OKD Job.
#
# reindex
#   One-shot bulk rebuild executed by an OKD Job using parallel_sync. It
#   creates and populates a new physical index, verifies the backfill
#   actually finished, then publishes the alias and drops what it superseded.
#
# producer
#   Single replica that produces change events. Only ever follows an alias
#   that a previous `reindex` Job already published.
#
# consumer
#   Horizontally scalable workers that wait until all aliases are published.

SCHEMA_PATH="${SCHEMA_PATH:-/app/schema.json}"
REINDEX_SCHEMA="${REINDEX_SCHEMA:-/tmp/schema.reindex.json}"
RESOLVED_SCHEMA="${RESOLVED_SCHEMA:-/tmp/schema.resolved.json}"
PGSYNC_ROLE="${PGSYNC_ROLE:-}"

log() {
  printf '%s\n' "### $*"
}

fail() {
  printf '%s\n' "ERROR: $*" >&2
  exit 1
}

require_env() {
  name="$1"
  eval "value=\${${name}:-}"
  [ -n "${value}" ] || fail "required environment variable ${name} is not set"
}

resolve_schema_from() {
  role="$1"
  source_schema="$2"
  shift 2

  [ -r "${source_schema}" ] || \
    fail "schema is not readable: ${source_schema}"

  python3 /app/scripts/resolve_schema.py \
    --role "${role}" \
    --schema "${source_schema}" \
    --out "${RESOLVED_SCHEMA}" \
    "$@"
}

resolve_schema() {
  role="$1"
  shift

  resolve_schema_from \
    "${role}" \
    "${SCHEMA_PATH}" \
    "$@"
}

prepare_reindex_schema() {
  targets="${REINDEX_TARGETS-all}"

  log "preparing reindex schema"
  log "requested reindex targets: ${targets}"

  # The filtered runtime schema must never overwrite the source schema.
  [ "${REINDEX_SCHEMA}" != "${SCHEMA_PATH}" ] || \
    fail "REINDEX_SCHEMA must be different from SCHEMA_PATH"

  # Never reuse a schema generated by a previous attempt.
  rm -f "${REINDEX_SCHEMA}"

  if ! python3 /app/scripts/filter_schema.py \
      --schema "${SCHEMA_PATH}" \
      --targets "${targets}" \
      --out "${REINDEX_SCHEMA}"
  then
    rm -f "${REINDEX_SCHEMA}"
    fail "failed to prepare reindex schema"
  fi

  [ -s "${REINDEX_SCHEMA}" ] || \
    fail "filtered reindex schema is empty: ${REINDEX_SCHEMA}"

  log "filtered reindex schema: ${REINDEX_SCHEMA}"
}

require_positive_integer() {
    name="$1"
    case "${name}" in
        ''|*[!A-Za-z0-9_]*)
            fail "invalid environment variable name: ${name}"
            ;;
    esac
    eval "value=\${${name}:-}"
    case "${value}" in
        ''|*[!0-9]*|0)
            fail "${name} must be a positive integer"
            ;;
    esac
}

[ -r "${SCHEMA_PATH}" ] || fail "schema is not readable: ${SCHEMA_PATH}"
require_env APP_ENV
require_env DB_NAME
require_env ELASTICSEARCH_URL
require_env REDIS_HOST

case "${PGSYNC_ROLE}" in
  bootstrap)
    require_env PG_URL

    log "resolving currently published index generation for bootstrap"

    # Standalone bootstrap never creates a new physical index.
    # It only operates against the generation currently published
    # through the Elasticsearch alias.
    resolve_schema bootstrap

    log "running one-shot bootstrap against published generation"
    log "resolved schema: ${RESOLVED_SCHEMA}"

    exec bootstrap --config "${RESOLVED_SCHEMA}"
    ;;

  reindex)
    require_env PG_URL

    PARALLEL_SYNC_MODE="${PARALLEL_SYNC_MODE:-multiprocess}"
    PARALLEL_SYNC_PROCESSES="${PARALLEL_SYNC_PROCESSES:-2}"

    case "${PARALLEL_SYNC_MODE}" in
        synchronous|multithreaded|multiprocess|\
        multithreaded_async|multiprocess_async)
            ;;
        *)
            fail "unsupported PARALLEL_SYNC_MODE: ${PARALLEL_SYNC_MODE}"
            ;;
    esac

    require_positive_integer PARALLEL_SYNC_PROCESSES

    # 1. Select the scope of this reindex.
    # Build the schema scope for this reindex execution.
    # REINDEX_TARGETS=all preserves the existing full-reindex behavior,
    # while specific targets limit the operation to those indexes.
    prepare_reindex_schema

    # 2. Resolve physical generations for the selected indexes.
    # Reindex is the only role allowed to allocate a new timestamped
    # physical index or resume an unpublished incomplete generation.
    # Only the indexes selected by REINDEX_TARGETS are resolved here.
    log "resolving new or resumable physical index generation for reindex"

    if ! resolve_schema_from \
        reindex \
        "${REINDEX_SCHEMA}"
    then
        fail "failed to resolve reindex schema"
    fi

    log "resolved schema: ${RESOLVED_SCHEMA}"


    #3. Bootstrap only the physical generations selected for this reindex.
    # This prepares the PGSync PostgreSQL objects and replication slots
    # associated with the selected timestamped target indexes.
    log "bootstrapping PGSync objects for selected reindex targets"

    if ! bootstrap --config "${RESOLVED_SCHEMA}"; then
        fail "bootstrap failed for reindex generation"
    fi

    # 4. Backfill the selected indexes.
    log "starting parallel reindex"
    log "mode: ${PARALLEL_SYNC_MODE}"
    log "processes/threads: ${PARALLEL_SYNC_PROCESSES}"

    if ! parallel_sync \
        -c "${RESOLVED_SCHEMA}" \
        -m "${PARALLEL_SYNC_MODE}" \
        -n "${PARALLEL_SYNC_PROCESSES}"
    then
        fail "parallel_sync failed"
    fi

    # 5. Validate, publish aliases and clean stale generations.
    log "finalizing selected reindex targets"

    if ! python3 /app/scripts/finalize_reindex.py \
        --schema "${RESOLVED_SCHEMA}"
    then
        fail "finalize_reindex failed"
    fi

    log "reindex completed and published"
    ;;

  producer)
    require_env PG_URL
    log "resolving physical index names for producer"
    # Initial indexing and alias publication are always done by the reindex
    # Job now, so the producer only ever follows an alias that already
    # exists -- it does not bootstrap and does not run a watcher.
    resolve_schema producer

    log "starting producer"
    exec pgsync --config "${RESOLVED_SCHEMA}" --daemon --producer
    ;;

  consumer)
    require_env PG_URL
    NUM_WORKERS="${NUM_WORKERS:-2}"
    require_positive_integer NUM_WORKERS

    log "waiting for the producer to publish all aliases"
    resolve_schema consumer --wait

    log "starting consumer with workers: ${NUM_WORKERS:-2}"
    exec pgsync --config "${RESOLVED_SCHEMA}" --daemon --consumer -n "${NUM_WORKERS:-2}"
    ;;

  teardown)
    require_env PG_URL
    expected_confirmation="teardown:${APP_ENV}:${DB_NAME}"
    if [ "${PGSYNC_TEARDOWN_CONFIRM:-}" != "${expected_confirmation}" ]; then
        fail "teardown requires PGSYNC_TEARDOWN_CONFIRM=${expected_confirmation}"
    fi

    log "resolving currently published physical indexes for teardown"
    # Teardown targets the indexes currently published through aliases.
    # It must not allocate new physical index names.
    resolve_schema producer

    log "starting destructive PGSync teardown"
    log "environment: ${APP_ENV}"
    log "database: ${DB_NAME}"
    log "resolved schema: ${RESOLVED_SCHEMA}"
    if bootstrap \
        --config "${RESOLVED_SCHEMA}" \
        --teardown
    then
        log "PGSync teardown completed successfully"
    else
        status=$?
        fail "PGSync teardown failed with exit code ${status}"
    fi
    ;;

  *)
    fail "PGSYNC_ROLE must be bootstrap, teardown, reindex, producer, or consumer (got: '${PGSYNC_ROLE}')"
    ;;
esac
